In [1]:
#load important packages or libs
import cv2 
import numpy as np

# 1.For Binary or Gray Level Images

## 1.1 binary 

### 1 ---> 0
### 0 ---> 1

# 1.2 Gray Scale Uint8

### new pixel value = 255 - current pixel value

## Example : 1

In [2]:
img = cv2.imread(r"Images/rice.PNG")
img_resize = cv2.resize(img, (600, 600))

In [3]:
img.dtype

dtype('uint8')

In [4]:
img[200,210]

array([0, 0, 0], dtype=uint8)

In [5]:
img_negative = cv2.bitwise_not(img)
img_negative_resize = cv2.resize(img_negative, (600, 600))

In [6]:
img_negative[200,210]

array([255, 255, 255], dtype=uint8)

In [7]:
cv2.imshow("img",img_resize)
cv2.imshow("img_negative",img_negative_resize )
cv2.waitKey(0)
cv2.destroyAllWindows()

## Example : 2 

In [8]:
img = cv2.imread(r"Images/grayscale.PNG")
img_resize = cv2.resize(img, (600, 600))

In [9]:
img.dtype

dtype('uint8')

In [10]:
img[200,200]

array([99, 99, 99], dtype=uint8)

In [11]:
img_negative = cv2.bitwise_not(img)
img_negative_resize = cv2.resize(img_negative, (600, 600))

In [12]:
img_negative[200,200]

array([156, 156, 156], dtype=uint8)

In [13]:
cv2.imshow("img",img_resize)
cv2.imshow("img_negative",img_negative_resize )
cv2.waitKey(0)
cv2.destroyAllWindows()