In [1]:
#load important packages or libs
import cv2 
import numpy as np

# Using Numpy

In [34]:
img = cv2.imread(r"Images/Dog.PNG",0)
#img = img/255.0

In [35]:
img.dtype

dtype('uint8')

In [36]:
img[250,250]

162

In [38]:
img

array([[  0,   0,   0, ..., 177, 176, 180],
       [  0,   0,   0, ..., 167, 167, 167],
       [  0,   0,   0, ..., 170, 170, 170],
       ...,
       [  0,   0,   0, ..., 110, 135, 158],
       [  0,   0,   0, ..., 106, 115, 138],
       [  0,   0,   0, ..., 131, 120,  96]], dtype=uint8)

In [46]:
np.log1p(img)
#ln(96) = 4.574

array([[0.   , 0.   , 0.   , ..., 5.184, 5.176, 5.2  ],
       [0.   , 0.   , 0.   , ..., 5.125, 5.125, 5.125],
       [0.   , 0.   , 0.   , ..., 5.14 , 5.14 , 5.14 ],
       ...,
       [0.   , 0.   , 0.   , ..., 4.71 , 4.914, 5.07 ],
       [0.   , 0.   , 0.   , ..., 4.67 , 4.754, 4.934],
       [0.   , 0.   , 0.   , ..., 4.883, 4.797, 4.574]], dtype=float16)

In [42]:
img_log = np.uint8(np.log1p(img))
img_log

array([[0, 0, 0, ..., 5, 5, 5],
       [0, 0, 0, ..., 5, 5, 5],
       [0, 0, 0, ..., 5, 5, 5],
       ...,
       [0, 0, 0, ..., 4, 4, 5],
       [0, 0, 0, ..., 4, 4, 4],
       [0, 0, 0, ..., 4, 4, 4]], dtype=uint8)

In [47]:
np.uint8(260)

4

In [68]:
np.uint8(-260)

252

In [83]:
cv2.imshow('Image before vs after Log Transformation',img_log)
cv2.waitKey(0)

-1

In [55]:
thresh1 = cv2.threshold(img_log,1,255,cv2.THRESH_BINARY)[1]
thresh1

array([[  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       ...,
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255]], dtype=uint8)

In [58]:
twoImagesWindows = cv2.hconcat((img,thresh1))
cv2.imshow('Image before vs after Log Transformation',twoImagesWindows)
cv2.waitKey(0)

-1

In [66]:
thresh1 = cv2.threshold(img_log,2,255,cv2.THRESH_BINARY)[1]
twoImagesWindows = cv2.hconcat((img,thresh1))
cv2.imshow('Image before vs after Log Transformation',twoImagesWindows)
cv2.waitKey(0)

-1

# using Log